### ISSUE TITLE
Breaking change to API ? 

### ISSUE THREAD

**Issue by gkowalski** [all-of-us/raw-data-repository#3987]
Our Pipeline failed starting Oct 3 . Was there a Breaking change to the API ? we get a 403 error calling the API with : 

https://all-of-us-rdr-prod.appspot.com/rdr/v1/ParticipantSummary?_sort=participantId&_count=1000&awardee=WISCONSIN

**Comment by eankumah** [comment]
@gkowalski no changes have been made to the endpoint, it appears something may have changed on your end and the endpoint your traffic is coming from is not on our allowed white list, so if you can please look into that on your end.  For site issues with the endpoint please reach out to drcsupport@vumc.org

**Comment by gkowalski** [comment]
Ha , didn't cross my mind  the IP Address of our server would change , thanks alot admin ... ;-) and you for pointing this out.
